/**
 * Plantillas de primera ronda de playoffs por cantidad inicial de parejas del torneo.
 *
 * Bracket prefijado: cada partido es { team1: "1A", team2: "2B" | null }.
 * "1A" = 1ro grupo A, "2B" = 2do grupo B, "3A" = 3ro grupo A (letra = orden de zona).
 * Clave = cantidad inicial de parejas (`totalPairs`; no clasificados).
 */

export type PredefinedFirstRoundMatch = { team1: string; team2: string | null };

export const PREDEFINED_FIRST_ROUND_BRACKETS: Record<number, PredefinedFirstRoundMatch[]> = {
  8: [
    { team1: "1A", team2: null },
    { team1: "2B", team2: "3A" },
    { team1: "1B", team2: null },
    { team1: "2A", team2: "3B" },
  ],
  9: [
    { team1: "1A", team2: null },
    { team1: "2C", team2: "2B" },
    { team1: "1B", team2: null },
    { team1: "1C", team2: "2A" },
  ],
  10: [
    { team1: "1A", team2: null },
    { team1: "2B", team2: "2C" },
    { team1: "1B", team2: "3A" },
    { team1: "1C", team2: "2A" },
  ],
  11: [
    { team1: "1A", team2: "3B" },
    { team1: "2C", team2: "2B" },
    { team1: "1B", team2: "3A" },
    { team1: "1C", team2: "2A" },
  ],
  12: [
    { team1: "1A", team2: "2B" },
    { team1: "1D", team2: "2C" },
    { team1: "1B", team2: "2A" },
    { team1: "1C", team2: "2D" },
  ],
  13: [
    { team1: "1A", team2: null },
    { team1: "2B", team2: "3A" },
    { team1: "1D", team2: null },
    { team1: "2C", team2: null },
    { team1: "1B", team2: null },
    { team1: "2A", team2: null },
    { team1: "1C", team2: null },
    { team1: "2D", team2: null },
  ],
  14: [
    { team1: "1A", team2: null },
    { team1: "2B", team2: "3A" },
    { team1: "1D", team2: null },
    { team1: "2C", team2: null },
    { team1: "1B", team2: null },
    { team1: "2A", team2: "3B" },
    { team1: "1C", team2: null },
    { team1: "2D", team2: null },
  ],
  15: [
    { team1: "1A", team2: null },
    { team1: "2D", team2: "2B" },
    { team1: "1D", team2: null },
    { team1: "1E", team2: null },
    { team1: "1B", team2: null },
    { team1: "2C", team2: "2A" },
    { team1: "1C", team2: null },
    { team1: "2E", team2: null },
  ],
  16: [
    { team1: "1A", team2: null },
    { team1: "2C", team2: "2B" },
    { team1: "1D", team2: null },
    { team1: "1E", team2: null },
    { team1: "1B", team2: null },
    { team1: "2D", team2: "2A" },
    { team1: "1C", team2: null },
    { team1: "2E", team2: "3A" },
  ],
  17: [
    { team1: "1A", team2: null },
    { team1: "2C", team2: "2B" },
    { team1: "1D", team2: null },
    { team1: "1E", team2: "3B" },
    { team1: "1B", team2: null },
    { team1: "2D", team2: "2A" },
    { team1: "1C", team2: null },
    { team1: "2E", team2: "3A" },
  ],
  18: [
    { team1: "1A", team2: null },
    { team1: "2F", team2: "2B" },
    { team1: "1D", team2: null },
    { team1: "1E", team2: "2C" },
    { team1: "1B", team2: null },
    { team1: "2E", team2: "2D" },
    { team1: "1C", team2: null },
    { team1: "1F", team2: "2A" },
  ],
  19: [
    { team1: "1A", team2: null },
    { team1: "2F", team2: "2B" },
    { team1: "1D", team2: "3A" },
    { team1: "1E", team2: "2C" },
    { team1: "1B", team2: null },
    { team1: "2E", team2: "2D" },
    { team1: "1C", team2: null },
    { team1: "1F", team2: "2A" },
  ],
  20: [
    { team1: "1A", team2: null },
    { team1: "2F", team2: "2B" },
    { team1: "1D", team2: "2C" },
    { team1: "1E", team2: "3B" },
    { team1: "1B", team2: null },
    { team1: "2E", team2: "2A" },
    { team1: "1C", team2: "2D" },
    { team1: "1F", team2: "3A" },
  ],
  21: [
    { team1: "1A", team2: null },
    { team1: "2G", team2: "2B" },
    { team1: "1D", team2: "2C" },
    { team1: "1E", team2: "2F" },
    { team1: "1B", team2: null },
    { team1: "1G", team2: "2A" },
    { team1: "1C", team2: "2D" },
    { team1: "1F", team2: "2E" },
  ],
  22: [
    { team1: "1A", team2: null },
    { team1: "2G", team2: "2B" },
    { team1: "1D", team2: "2C" },
    { team1: "1E", team2: "2F" },
    { team1: "1B", team2: "3A" },
    { team1: "1G", team2: "2A" },
    { team1: "1C", team2: "2D" },
    { team1: "1F", team2: "2E" },
  ],
  23: [
    { team1: "1A", team2: "3B" },
    { team1: "2G", team2: "2F" },
    { team1: "1D", team2: "2B" },
    { team1: "1E", team2: "2C" },
    { team1: "1B", team2: "3A" },
    { team1: "1G", team2: "2E" },
    { team1: "1C", team2: "2A" },
    { team1: "1F", team2: "2D" },
  ],
  24: [
    { team1: "1A", team2: "2B" },
    { team1: "1H", team2: "2G" },
    { team1: "1D", team2: "2C" },
    { team1: "1E", team2: "2F" },
    { team1: "1B", team2: "2A" },
    { team1: "1G", team2: "2H" },
    { team1: "1C", team2: "2D" },
    { team1: "1F", team2: "2E" },
  ],
};
